"""
Classifies: CHEBI:26208 polyunsaturated fatty acid
"""
"""
Classifies: polyunsaturated fatty acid
"""

from rdkit import Chem
from rdkit.Chem import rdMolDescriptors

def is_polyunsaturated_fatty_acid(smiles: str):
    """
    Determines if a molecule is a polyunsaturated fatty acid based on its SMILES string.
    A polyunsaturated fatty acid is a fatty acid containing more than one double bond.
    
    Args:
        smiles (str): SMILES string of the molecule
    
    Returns:
        bool: True if molecule is a polyunsaturated fatty acid, False otherwise
        str: Reason for classification
    """
    # Parse SMILES
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return False, "Invalid SMILES string"
    
    # Check for carboxylic acid group
    carboxylic_acid = Chem.MolFromSmarts("C(=O)[O,H]")  # Matches -C(=O)O[H]
    if not mol.HasSubstructMatch(carboxylic_acid):
        return False, "No carboxylic acid group found"
    
    # Get the carboxylic acid carbon atom index
    matches = mol.GetSubstructMatches(carboxylic_acid)
    carboxylic_acid_atoms = [atom_idx for match in matches for atom_idx in match]
    
    # Calculate the total number of carbons excluding the carboxyl carbon
    num_carbons = sum(1 for atom in mol.GetAtoms() 
                      if atom.GetAtomicNum() == 6 and atom.GetIdx() not in carboxylic_acid_atoms)
    if num_carbons < 8:
        return False, f"Chain too short ({num_carbons} carbons), fatty acids typically have at least 8 carbons"
    
    # Count the number of carbon-carbon double bonds
    double_bond_count = 0
    for bond in mol.GetBonds():
        if bond.GetBondType() == Chem.rdchem.BondType.DOUBLE:
            begin_atom = bond.GetBeginAtom()
            end_atom = bond.GetEndAtom()
            if begin_atom.GetAtomicNum() == 6 and end_atom.GetAtomicNum() == 6:
                double_bond_count += 1
    
    if double_bond_count < 2:
        return False, f"Contains {double_bond_count} double bond(s), must have more than one"
    
    # Check for rings
    if mol.GetRingInfo().NumRings() > 0:
        return False, "Contains ring structures, not a typical fatty acid"
    
    return True, "Contains carboxylic acid and more than one carbon-carbon double bond"

__metadata__ = {
    'chemical_class': {
        'name': 'polyunsaturated fatty acid',
        'definition': 'Any fatty acid containing more than one double bond. Acids in this group are reported to have cardioprotective effects; and levels are lowered in chronic fatigue syndrome.'
    },
    'source': 'Generated by OpenAI Assistant'
}