"""
Classifies: CHEBI:1722 3beta-hydroxy-Delta(5)-steroid
"""
 - (25R)-3beta-hydroxycholest-5-en-26-oic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCC[C@@H](C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (22R)-22-hydroxycholesterol: SMILES: [H][C@@]1(CC[C@@]2([H])[C@]3([H])CC=C4C[C@@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)[C@H](O)CCC(C)C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-24-hydroxycholesterol: SMILES: [H][C@@]1(CC[C@@]2([H])[C@]3([H])CC=C4C[C@@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)CC[C@H](O)C(C)C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - 3beta,7alpha-dihydroxy-5-cholenoic acid: SMILES: C1[C@]2([C@H](C[C@H](C1)O)O)CC[C@H]3[C@H]2CC=C2C[C@H](O)CC[C@]23C
 - 3beta,7alpha-dihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(CC=C2C[C@H](C1)O)[H])(CC[C@@]4([C@H](C)CCCC(C)C(O)=O)[H])[H])C)[H])C
 - (24R)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (24S)-3beta,24-dihydroxycholest-5-en-7-one: SMILES: CC(C)C[C@H](O)C[C@@H](C)[C@H]1CC[C@H]2[C@@H]3C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - (25R)-3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@@H](CCC(O)=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxy-5-chol