"""
Classifies: CHEBI:16337 phosphatidic acid
"""
 - PA(20:3(8Z,11Z,14Z)/18:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCC)COC(=O)CCCCCC/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(18:3(6Z,9Z,12Z)/18:3(6Z,9Z,12Z)): SMILES: P(OC[C@H](OC(=O)CCCC/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCC/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(22:0/18:3(9Z,12Z,15Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:3(9Z,12Z,15Z)/18:3(9Z,12Z,15Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCC/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/18:1(11Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCC/C=C\CCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(16:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/18:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(20:3(8Z,11Z,14Z)/18:2(9Z,12Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\CCCCC)COC(=O)CCCCCC/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(18:1(9Z)/20:5(5Z,8Z,11Z,14Z,17Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCC/C=C\CCCCCCCC)(O)(O)=O
 - PA(18:1(9Z)/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCC/C=C\CCCCCCCC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(20:0/20:5(5Z,8Z,11Z,14Z,17Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:0/18:4(6Z,9Z,12Z,15Z)): SMILES: P(OC[C@H](OC(=O)CCCC/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:3(6Z,9Z,12Z)/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCC/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(20:5(5Z,8Z,11Z,14Z,17Z)/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(20:5(5Z,8Z,11Z,14Z,17Z)/20:5(5Z,8Z,11Z,14Z,17Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(16:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(16:0/18:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:1(9Z)/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCCCCC/C=C\CCCCCCCC)(O)(O)=O
 - PA(18:0/18:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:1(9Z)/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCCCC/C=C\CCCCCCCC)(O)(O)=O
 - PA(18:1(9Z)/18:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCC)COC(=O)CCCCCCC/C=C\CCCCCCCC)(O)(O)=O
 - PA(16:0/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:0/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(14:0/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCC)(O)(O)=O
 - PA(12:0/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(10:0/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(8:0/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(6:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CCCCC)(O)(O)=O
 - PA(4:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CCC)(O)(O)=O
 - PA(2:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)C)(O)(O)=O
 - PA(0:0/0:0): SMILES: P(OC[C@H](O)CO)(O)(O)=O
 - PA(22:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(24:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(20:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(24:1(15Z)/24:1(15Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC/C=C\CCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC/C=C\CCCC)(O)(O)=O
 - PA(20:1(11Z)/20:1(11Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC/C=C\CCCC)COC(=O)CCCCCCCCCCCCCCCCC/C=C\CCCC)(O)(O)=O
 - PA(18:1(11Z)/18:1(11Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCC/C=C\CC)COC(=O)CCCCCCCCCCCCCC/C=C\CC)(O)(O)=O
 - PA(16:1(9Z)/16:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCC/C=C\CCCC)COC(=O)CCCCCCCCCC/C=C\CCCC)(O)(O)=O
 - PA(14:1(9Z)/14:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCC/C=C\CCCC)COC(=O)CCCCCCCC/C=C\CCCC)(O)(O)=O
 - PA(12:1(9Z)/12:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCC/C=C\CCCC)COC(=O)CCCCCC/C=C\CCCC)(O)(O)=O
 - PA(10:1(9Z)/10:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCC/C=C\CCCC)COC(=O)CCCC/C=C\CCCC)(O)(O)=O
 - PA(8:1(9Z)/8:1(9Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\CCCC)COC(=O)CC/C=C\CCCC)(O)(O)=O
 - PA(6:1(9Z)/6:1(9Z)): SMILES: P(OC[C@H](OC(=O)C/C=C\CCCC)COC(=O)C/C=C\CCCC)(O)(O)=O
 - PA(4:1(9Z)/4:1(9Z)): SMILES: P(OC[C@H](OC(=O)/C=C\CCCC)COC(=O)/C=C\CCCC)(O)(O)=O
 - PA(2:1(9Z)/2:1(9Z)): SMILES: P(OC[C@H](OC(=O)/C=C\C)COC(=O)/C=C\C)(O)(O)=O
 - PA(0:0/0:0): SMILES: P(OC[C@H](O)CO)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(18:2(9Z,12Z)/18:2(9Z,12Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\CCCCC)COC(=O)CCCCCCC/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(16:0/18:2(9Z,12Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:2(9Z,12Z)/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCCCCC/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(14:0/16:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCC/C=C\CCCC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(16:1(9Z)/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCCCCCCCCC/C=C\CCCC)(O)(O)=O
 - PA(12:0/14:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCC/C=C\CCCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(14:1(9Z)/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCCCCCCC/C=C\CCCC)(O)(O)=O
 - PA(10:0/12:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCC/C=C\CCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(12:1(9Z)/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CCCCCC/C=C\CCCC)(O)(O)=O
 - PA(8:0/10:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCC/C=C\CCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(10:1(9Z)/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCC/C=C\CCCC)(O)(O)=O
 - PA(6:0/8:1(9Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\CCCC)COC(=O)CCCCC)(O)(O)=O
 - PA(8:1(9Z)/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CC/C=C\CCCC)(O)(O)=O
 - PA(4:0/6:1(9Z)): SMILES: P(OC[C@H](OC(=O)C/C=C\CCCC)COC(=O)CCC)(O)(O)=O
 - PA(6:1(9Z)/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)C/C=C\CCCC)(O)(O)=O
 - PA(2:0/4:1(9Z)): SMILES: P(OC[C@H](OC(=O)/C=C\CCCC)COC(=O)C)(O)(O)=O
 - PA(4:1(9Z)/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)/C=C\CCCC)(O)(O)=O
 - PA(0:0/2:1(9Z)): SMILES: P(OC[C@H](OC(=O)/C=C\C)CO)(O)(O)=O
 - PA(2:1(9Z)/0:0): SMILES: P(OC[C@H](O)COC(=O)/C=C\C)(O)(O)=O
 - PA(20:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(22:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(20:0/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(16:0/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(14:0/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(12:0/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(10:0/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(8:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(6:0/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCC)(O)(O)=O
 - PA(4:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CCC)(O)(O)=O
 - PA(2:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)C)(O)(O)=O
 - PA(0:0/0:0): SMILES: P(OC[C@H](O)CO)(O)(O)=O
 - PA(22:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(24:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(20:0/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(16:0/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(12:0/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(10:0/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(8:0/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(6:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CCCCC)(O)(O)=O
 - PA(4:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CCC)(O)(O)=O
 - PA(2:0/0:0): SMILES: P(OC[C@H](O)COC(=O)C)(O)(O)=O
 - PA(0:0/2:0): SMILES: P(OC[C@H](OC(=O)C)CO)(O)(O)=O
 - PA(24:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(20:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(18:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(16:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(14:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(12:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(10:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(8:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(6:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(4:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(2:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)C)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(0:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)CO)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/0:0): SMILES: P(OC[C@H](O)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(24:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(22:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(18:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(16:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(14:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(12:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(10:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(20:4(5Z,8Z,11Z,14Z)/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)(O)(O)=O
 - PA(8:0/20:4(5Z,8Z,11Z,14Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(22:6(4Z,7Z,10Z,13Z,16Z,19Z)/22:6(4Z,7Z,10Z,13Z,16Z,19Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(20:5(5Z,8Z,11Z,14Z,17Z)/20:5(5Z,8Z,11Z,14Z,17Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(18:4(6Z,9Z,12Z,15Z)/18:4(6Z,9Z,12Z,15Z)): SMILES: P(OC[C@H](OC(=O)CCCC/C=C\C/C=C\C/C=C\C/C=C\CC)COC(=O)CCCC/C=C\C/C=C\C/C=C\C/C=C\CC)(O)(O)=O
 - PA(16:4(4Z,7Z,10Z,13Z)/16:4(4Z,7Z,10Z,13Z)): SMILES: P(OC[C@H](OC(=O)CCCC/C=C\C/C=C\C/C=C\C/C=C\CCCC)COC(=O)CCCC/C=C\C/C=C\C/C=C\C/C=C\CCCC)(O)(O)=O
 - PA(14:4(4Z,7Z,10Z,13Z)/14:4(4Z,7Z,10Z,13Z)): SMILES: P(OC[C@H](OC(=O)CCCC/C=C\C/C=C\C/C=C\C/C=C\CCCC)COC(=O)CCCC/C=C\C/C=C\C/C=C\C/C=C\CCCC)(O)(O)=O
 - PA(12:4(3Z,6Z,9Z,12Z)/12:4(3Z,6Z,9Z,12Z)): SMILES: P(OC[C@H](OC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCC)COC(=O)CCC/C=C\C/C=C\C/C=C\C/C=C\CCCC)(O)(O)=O
 - PA(10:4(2Z,5Z,8Z,11Z)/10:4(2Z,5Z,8Z,11Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\CCCC)COC(=O)CC/C=C\C/C=C\C/C=C\C/C=C\CCCC)(O)(O)=O
 - PA(8:4(2Z,5Z,8Z,11Z)/8:4(2Z,5Z,8Z,11Z)): SMILES: P(OC[C@H](OC(=O)C/C=C\C/C=C\C/C=C\C/C=C\CCCC)COC(=O)C/C=C\C/C=C\C/C=C\C/C=C\CCCC)(O)(O)=O
 - PA(6:4(2Z,5Z,8Z,11Z)/6:4(2Z,5Z,8Z,11Z)): SMILES: P(OC[C@H](OC(=O)/C=C\C/C=C\C/C=C\C/C=C\CCCC)COC(=O)/C=C\C/C=C\C/C=C\C/C=C\CCCC)(O)(O)=O
 - PA(4:4(2Z,5Z,8Z,11Z)/4:4(2Z,5Z,8Z,11Z)): SMILES: P(OC[C@H](OC(=O)/C=C\C/C=C\C/C=C\C/C=C\CCCC)COC(=O)/C=C\C/C=C\C/C=C\C/C=C\CCCC)(O)(O)=O
 - PA(2:4(2Z,5Z,8Z,11Z)/2:4(2Z,5Z,8Z,11Z)): SMILES: P(OC[C@H](OC(=O)/C=C\C/C=C\C/C=C\C/C=C\C)COC(=O)/C=C\C/C=C\C/C=C\C/C=C\C)(O)(O)=O
 - PA(0:4/0:4): SMILES: P(OC[C@H](OC(=O)/C=C\C/C=C\C/C=C\C/C=C\C)CO)(O)(O)=O
 - PA(24:0/18:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCC/C=C\CCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(18:1(9Z)/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCC/C=C\CCCCCCCC)(O)(O)=O
 - PA(22:0/16:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCC/C=C\CCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(16:1(9Z)/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCC/C=C\CCCC)(O)(O)=O
 - PA(20:0/14:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCCCC/C=C\CCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(14:1(9Z)/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCC/C=C\CCCC)(O)(O)=O
 - PA(18:0/12:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCCCC/C=C\CCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(12:1(9Z)/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCCC/C=C\CCCC)(O)(O)=O
 - PA(16:0/10:1(9Z)): SMILES: P(OC[C@H](OC(=O)CCCC/C=C\CCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(10:1(9Z)/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCC/C=C\CCCC)(O)(O)=O
 - PA(14:0/8:1(9Z)): SMILES: P(OC[C@H](OC(=O)CC/C=C\CCCC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(8:1(9Z)/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CC/C=C\CCCC)(O)(O)=O
 - PA(12:0/6:1(9Z)): SMILES: P(OC[C@H](OC(=O)C/C=C\CCCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(6:1(9Z)/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)C/C=C\CCCC)(O)(O)=O
 - PA(10:0/4:1(9Z)): SMILES: P(OC[C@H](OC(=O)/C=C\CCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(4:1(9Z)/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)/C=C\CCCC)(O)(O)=O
 - PA(8:0/2:1(9Z)): SMILES: P(OC[C@H](OC(=O)/C=C\C)COC(=O)CCCCCCC)(O)(O)=O
 - PA(2:1(9Z)/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)/C=C\C)(O)(O)=O
 - PA(6:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCC)(O)(O)=O
 - PA(0:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)CO)(O)(O)=O
 - PA(24:0/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(16:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(22:0/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(14:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(20:0/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(12:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(18:0/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(10:0/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(16:0/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(8:0/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(14:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(6:0/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCCCC)(O)(O)=O
 - PA(12:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(4:0/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCC)(O)(O)=O
 - PA(10:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(2:0/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)C)(O)(O)=O
 - PA(8:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCCCC)(O)(O)=O
 - PA(0:0/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)CO)(O)(O)=O
 - PA(24:0/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(14:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(22:0/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(12:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(20:0/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(10:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(18:0/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(8:0/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(16:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(6:0/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCCCC)(O)(O)=O
 - PA(14:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(4:0/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)CCC)(O)(O)=O
 - PA(12:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(2:0/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)C)(O)(O)=O
 - PA(10:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(0:0/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)CO)(O)(O)=O
 - PA(24:0/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(12:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(22:0/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(10:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(20:0/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(8:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(18:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(6:0/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCCCC)(O)(O)=O
 - PA(16:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(4:0/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)CCC)(O)(O)=O
 - PA(14:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CCCCCCCCCCCCC)(O)(O)=O
 - PA(2:0/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCC)COC(=O)C)(O)(O)=O
 - PA(12:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(0:0/12:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)CO)(O)(O)=O
 - PA(24:0/10:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(10:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCCCC)(O)(O)=O
 - PA(22:0/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(8:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(20:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(6:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCCCC)(O)(O)=O
 - PA(18:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(4:0/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)CCC)(O)(O)=O
 - PA(16:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(2:0/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)COC(=O)C)(O)(O)=O
 - PA(14:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCC)(O)(O)=O
 - PA(0:0/14:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCC)CO)(O)(O)=O
 - PA(24:0/8:0): SMILES: P(OC[C@H](OC(=O)CCCCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(8:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCCCC)(O)(O)=O
 - PA(22:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(6:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCC)(O)(O)=O
 - PA(20:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(4:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)CCC)(O)(O)=O
 - PA(18:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(2:0/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)COC(=O)C)(O)(O)=O
 - PA(16:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCCCCCC)(O)(O)=O
 - PA(0:0/16:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCC)CO)(O)(O)=O
 - PA(24:0/6:0): SMILES: P(OC[C@H](OC(=O)CCCCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(6:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCCCC)(O)(O)=O
 - PA(22:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(4:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)CCC)(O)(O)=O
 - PA(20:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(2:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)COC(=O)C)(O)(O)=O
 - PA(18:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(0:0/18:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCC)CO)(O)(O)=O
 - PA(24:0/4:0): SMILES: P(OC[C@H](OC(=O)CCC)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(4:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)CCC)(O)(O)=O
 - PA(22:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(2:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)COC(=O)C)(O)(O)=O
 - PA(20:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(0:0/20:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCC)CO)(O)(O)=O
 - PA(24:0/2:0): SMILES: P(OC[C@H](OC(=O)C)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(2:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)COC(=O)C)(O)(O)=O
 - PA(22:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(0:0/22:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCC)CO)(O)(O)=O
 - PA(24:0/0:0): SMILES: P(OC[C@H](O)COC(=O)CCCCCCCCCCCCCCCCCCCCCC)(O)(O)=O
 - PA(0:0/24:0): SMILES: P(OC[C@H](OC(=O)CCCCCCCCCCCCCCCCCCCCCC)CO)(O)(O)=O
 - PA(0:0/0:0): SMILES: P(OC[C@H](O)CO)(O)(O)=O
</think>

Okay, I need to create a function called is_phosphatidic_acid that checks if a given SMILES string represents a phosphatidic acid. From the definition, phosphatidic acid is a glycerol derivative where one hydroxyl is esterified with phosphoric acid and the other two with fatty acids. 

First, I should parse the SMILES into an RDKit molecule. If that fails, return invalid. Then, I need to check for the glycerol backbone. But wait, in phosphatidic acid, the glycerol has two ester groups (from fatty acids) and one phosphate group. 

So, the structure should have a central glycerol where two oxygens are part of ester groups (connected to fatty acids) and one oxygen connected to a phosphate group. The phosphate group is a phosphorus atom connected to four oxygen atoms, with one of them being part of the glycerol's oxygen.

I'll start by looking for the phosphate group. The phosphate in phosphatidic acid is usually a phosphoric acid ester, so the pattern would be something like O-P(=O)(O)-O connected to the glycerol.

Using SMARTS, maybe I can find the phosphate group attached to the glycerol. The glycerol part would be a three-carbon chain with two ester groups and one phosphate. The phosphate group should be connected via an oxygen to the glycerol's carbon.

Also, there should be two ester groups (-O-C=O) from the fatty acids. So I need to count two ester groups and one phosphate ester.

Let me outline the steps:

1. Check if the molecule has a phosphate group attached to the glycerol backbone.
2. Ensure there are exactly two ester groups (from fatty acids).
3. Verify the presence of fatty acid chains (long carbon chains) attached to the esters.
4. Check the molecular structure to confirm the glycerol backbone with the correct substitutions.

Possible SMARTS patterns:
- Phosphate group: [PX4](=O)([OX2])[OX2]
- Glycerol backbone with phosphate: Look for a carbon connected to the phosphate and two ester oxygens.
- Ester groups: [OX2]C(=O)[CX4].

Wait, the glycerol in phosphatidic acid is typically sn-glycerol-3-phosphate, so the phosphate is on the third carbon. The structure would be something like:
O-P(=O)(O)-O-CH2-CH(OOCR1)-CH2-OOCR2

But stereochemistry might vary, so maybe ignore stereo for simplicity.

So the SMARTS for the core could be something like:
C([OX2]P(=O)([OX2])[OX2])(COC(=O)*)COC(=O)*

But SMARTS can get complicated. Alternatively, find the phosphorus atom connected to four oxygens, with one oxygen connected to a carbon that's part of a glycerol-like structure.

Another approach: Find the phosphate group, check that it's connected to a glycerol backbone (three carbons with two ester groups).

Let me try to break it down:

1. Find the phosphorus atom with the phosphate group: P(=O)(O)(O)O-. But in the molecule, it's more like O-P(=O)(O-)O- connected to the glycerol.

2. The glycerol part: a central carbon connected to two other carbons, each with an ester group.

Alternatively, the glycerol backbone can be represented as [CH2]-[CH]-[CH2