"""
Classifies: CHEBI:15889 sterol
"""
 - 7alpha,27-dihydroxycholesterol: SMILES: [H][C@@]1(CC[C@@]2([H])[C@]3([H])[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)CCCC(C)CO
 - 5alpha-cholest-8-en-3beta-ol: SMILES: [H][C@@]12CC[C@]3([H])C(=C)CC[C@H](C3)[C@]1(C)CC[C@H](O)C2
 - 3beta,7alpha-dihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 7alpha-hydroxycholesterol: SMILES: [H][C@@]1(CC[C@@]2([H])[C@]3([H])[C@H](O)C=C4C[C@@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)CCCC(C)C
 - 25-hydroxycholesterol: SMILES: [H][C@@]1(CC[C@@]2([H])[C@]3([H])CC=C4C[C@@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)CCCC(C)(C)O
 - 7-dehydrocholesterol: SMILES: [H][C@@]1(CC[C@@]2([H])C3=CC=C4C[C@@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)CCCC(C)C
 - 3beta-hydroxycholest-5-en-7-one: SMILES: [H][C@@]1(CC[C@@]2([H])[C@]3([H])C(=O)C=C4C[C@@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)CCCC(C)C
 - 5alpha-cholest-8(14)-en-3beta-ol: SMILES: [H][C@@]12CC[C@]3([H])C(=C)CC[C@H](C3)[C@]1(C)CC[C@H](O)C2
 - 7-dehydrocampesterol: SMILES: [H][C@@]1(CC[C@@]2([H])C3=CC=C4C[C@@H](O)CC[C@]4(C)[C@@]3([H])CC[C@]12C)[C@H](C)CC[C@H](C)C(C)C
 - 3beta-hydroxy-5alpha-cholest-8(14)-en-15-one: SMILES: [H][C@@]12CC[C@]3([H])C(=C)CC[C@H](C3)[C@]1(C)CC[C@H](O)C2C(=O)C
 - 3beta,7alpha,12alpha-trihydroxy-5-cholestenoic acid: SMILES: C1[C@@]2([C@]3(CC[C@]4([C@]([C@@]3(C(C=C2C[C@H](C1)O)=O)[H])(CC[C@@]4([C@H](C)CCCC(=O)O)[H])[H])C)[H])C
 - 5alpha-cholest-8-en-3beta-ol: SMILES: [H][C@@]12CC=C3C[C@H](O)CC[C@]3(C)[C@@]1([H])CC[C@@]2(C)[C@H](C)CCCC(C)C
 - 5alpha-cholest-7-en-3beta-ol: SMILES: [H][C@@]12CC=C3CC[C@H](C)[C@]3(C)CC[C@H](O)[C@@]1(C)CC2
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 5alpha-cholestan-3beta-ol: SMILES: [H][C@@]12CCCC3C[C@H](O)CC[C@]3(C)[C@@]1([H])CC[C@@]2(C)[C@H](C)CCCC(C)C
 - 3beta,7alpha-dihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha,24-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha-dihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha-dihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-al: SMILES: C[C@H](CCC=O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-24-oic acid: SMILES: C[C@H](CCC(=O)O)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C.O
 - 3beta,7alpha,12alpha-trihydroxycholest-5-en-26-al: SMILES: C[C@H](C=O)CCC[C@@H](C)[C@H